sdm660-common: DeviceSettings: Define used libraries * Trigger build error in A14 build system
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
	- optional libraries in build system: []
	                 vs. in the manifest: []
	- tags in the manifest (/home/aditya/vos/out/target/common/obj/APPS/Doze_intermediates/manifest/AndroidManifest.xml):
		<uses-library android:name="androidx.window.extensions" android:required="false"/>
		<uses-library android:name="androidx.window.sidecar" android:required="false"/>

Signed-off-by: khirendra <khirendrapatel3@gmail.com>